### ISSUE TITLE
Conformance errors / General compliance: Element size 701787 is more than maximal permitted size 582942 (conf, offset 0x41FF5E1)

### ISSUE THREAD

**Issue by iconoclasthero** [MediaArea/MediaInfoLib#2285]
```
Conformance errors                       : 1
 General compliance                      : Element size 701787 is more than maximal permitted size 582942 (conf, offset 0x41FF5E1)
```

In adding a cover image to an ogg/opus file over a certain size I received this warning; reducing the cover size eliminated this.  
It does not appear that this number comes from the ogg/opus spec.

What is this error? Why does it matter?  Is it a real thing?  The files still work.

**Comment by JeromeMartinez** [comment]
Please a sample file.

**Comment by iconoclasthero** [comment]
Can we start with what the conformance error means?  Is it important?

**Comment by iconoclasthero** [comment]
Sent to 1 person
jerome@mediaarea.net
via wetransfer.

**Comment by JeromeMartinez** [comment]
> Can we start with what the conformance error means?

Not relevant here, I think, as it is not not for the OGG stream if I understood well.

>  Is it important?

If bug from MediaInfo, no

> Sent to 1 person

Your file is not demonstrating this issue, at least with MediaInfo 25.04.

> why the end there where it tries to look for a cover with mediainfo 

Currently MediaInfo does not support [FLAC style thumbnails in Vorbis comments](https://wiki.xiph.org/VorbisComment#METADATA_BLOCK_PICTURE), but I add that to my todo-list, as well as checking why MediaInfo finds a stream synchronization issue (not reported in the main report), I guess it is a MediaInfo issue (we quickly developed OGG support and not with big "comments", cover included, like that).

**Comment by JeromeMartinez** [comment]
> This is another example where mediainfo does not show that there's an attached image stream vs ffprobe

Sample file please.

**Comment by iconoclasthero** [comment]
> Your file is not demonstrating this issue, at least with MediaInfo 25.04.
The latest in sid is 25.03 so without having to build it myself I upgraded to that today.

Below:
1. check the version
2. remove the test output file
3. check for no cover in the input file (with ffprobe)
4. check the size of the file to embed
5. add the cover (with opustags) and echo confirmation
6. check for added cover (ffprobe)
7. show conformance error with mediainfo 25.03

```
$ hr; /usr/bin/mediainfo --version; hr; rm Pathogenesis\ --\ Audiobook-2.opus; \
ffprobe -hide_banner Pathogenesis\ --\ Audiobook.opus; hr; \
mediainfo Pathogenesis\ --\ Cover\ 01.jpg|grep Width -A1; hr; \
opustags --set-cover=Pathogenesis\ --\ Cover\ 01.jpg -o Pathogenesis\ --\ Audiobook-2.opus Pathogenesis\ --\ Audiobook.opus && echo cover\ added; hr; \
ffprobe -hide_banner Pathogenesis\ --\ Audiobook-2.opus 2>&1|grep Stream\ \#0\:1 -A3; hr; \
/usr/bin/mediainfo Pathogenesis\ --\ Audiobook-2.opus |grep Conformance -A 1;hr

#########################################################################################################
MediaInfo Command line, 
MediaInfoLib - v25.03
#########################################################################################################
Input #0, ogg, from 'Pathogenesis -- Audiobook.opus':
  Duration: 09:23:17.13, start: 0.000000, bitrate: 16 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 14.366000
      Metadata:
        title           : Intro Credits 
    Chapter #0:1: start 14.366000, end 1824.965000
      Metadata:
        title           : Introduction 
    Chapter #0:2: start 1824.965000, end 4568.449000
      Metadata:
        title           : Chapter 01: Paleolithic Plagues 
    Chapter #0:3: start 4568.449000, end 7680.712000
      Metadata:
        title           : Chapter 02: Neolithic Plagues 
    Chapter #0:4: start 7680.712000, end 11929.267000
      Metadata:
        title           : Chapter 03: Ancient Plagues 
    Chapter #0:5: start 11929.267000, end 16440.277000
      Metadata:
        title           : Chapter 04: Medieval  Plagues 
    Chapter #0:6: start 16440.277000, end 18529.701000
      Metadata:
        title           : Chapter 05: Colonial Plagues 
    Chapter #0:7: start 18529.701000, end 21413.758000
      Metadata:
        title           : Chapter 05: (cont.) Littlie Britain 
    Chapter #0:8: start 21413.758000, end 25439.517000
      Metadata:
        title           : Chapter 06: Revolutionary Plagues 
    Chapter #0:9: start 25439.517000, end 29173.053000
      Metadata:
        title           : Chapter 07: Industrial Plagues 
    Chapter #0:10: start 29173.053000, end 32815.474000
      Metadata:
        title           : Chapter 08: Plagues of Poverty 
    Chapter #0:11: start 32815.474000, end 33769.999000
      Metadata:
        title           : Conclusion 
    Chapter #0:12: start 33769.999000, end 33797.135000
      Metadata:
        title           : End Credits 
  Stream #0:0(English): Audio: opus, 48000 Hz, mono, fltp
      Metadata:
        encoder         : Lavc60.6.101 libopus
        track           : 1
        copyright       : Books on Tape
        title           : Pathogenesis
        artist          : Jonathan Kennedy
        album_artist    : Jonathan Kennedy
        composer        : Jonathan Kennedy
        album           : Pathogenesis: A History of the World in Eight Plagues
        subtitle        : A History of the World in Eight Plagues
        TIT3            : A History of the World in Eight Plagues
        Language        : English
        date            : 2023
        genre           : History; Politics & Social Sciences
        comment         : <p><b>NATIONAL BESTSELLER • A “gripping” (</b><b><i>The Washington Post</i></b><b>) account of how the major transformations in history—from the rise of </b><b><i>Homo sapiens</i></b><b> to the birth of capitalism—have been shaped not by humans 
        publisher       : Random House Audio
#########################################################################################################
Width                                    : 2 400 pixels
Height                                   : 2 400 pixels
#########################################################################################################
cover added
#########################################################################################################
  Stream #0:1: Video: mjpeg (Progressive), yuvj420p(pc, bt470bg/unknown/unknown), 2400x2400 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn (attached pic)
      Metadata:
        comment         : Cover (front)
#########################################################################################################
Conformance errors                       : 1
 General compliance                      : Element size 1706743 is more than maximal permitted size 582942 (conf, offset 0x42F5C92)
#########################################################################################################
```
Not sure why you're not getting the same error.

I sent 3 files:
- opus w/o cover
- 2400² px cover jpeg
- opus w/cover

You can try to attach the image with `opustags`, etc., so you can test at your leisure if you wish.  I'm going to leave the size reduction loop with the conformance check for now since the embedded cover still ends up sufficiently large....  I suspect that the cover of _Pathogenesis_ is particularly poorly compressed by jpeg because it's already a rather random image and thus causes problems.  I.e., most of the time there's no issue at the starting scale of 1200².

**Comment by JeromeMartinez** [comment]
>  I've sent both of these via wetransfer; have you not received them?

I got the OPUS file with the image, currently it is not supported (ignored) but we plan to support that (we have some code already for it, it needs more QA).

> Not sure why you're not getting the same error.

"mediainfo 25.03" is the clue (I can reproduce with this version but the bug showing a conformance error from another parser, which should not be there because this parser is not the final one, is fixed in 25.04).

**Comment by iconoclasthero** [comment]
Ok, I'll wait until I either build 25.04 or it shows up in the Debian repo before further comment on the conformance issue.

As I'm working on another book, there's an issue with how mediainfo reports out tags that are added after `METADATA_BLOCK_PICTURE`... i.e., **it doesn't**.  

I went through my normal script which adds the cover after retagging the file and then decided I wanted to change the description.  Mediainfo doesn't show anything for description/comment after `METADATA_BLOCK_PICTURE` and I hasten to guess that _any_ tag added after M_B_P will also be omitted.  

When you get around to updating this part of the OGG code, this should also be examined.  

NB: I asked the maintainer of opustags to make sure that M_B_P was at the end and the response was that it isn't part of the OGG spec and that it is an issue with how mediainfo parses the tags (which you basically confirm above).  Upon reflection, I believe that whether or not the spec requires M_B_P at the end, the parser should be able to handle tags regardless of their order.

I'll send an example in a moment....  The commands below check for a description with `mediainfo` and then remove the image with `opustags` and check again (the chapter index is suppressed with `grep -v`):

```
$ echo; hr; file="Violence and the Sacred -- Audiobook.opus"; \
opustags --delete comment --delete METADATA_BLOCK_PICTURE -i "$file" && 
  echo "Removed original comment and image (if present)"; hr; \
mi "$file" | grep -v '^Menu$' | grep -v '^[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}'; hr; \
opustags --set-cover "${file/Audiobook.opus/Cover 01.jpg}" -i "$file"  &&
  echo "Set cover with opustags"; hr; \
opustags --set comment="$(jq .description metadata.json)" -i "$file" &&
  echo "Set description/comment with opustags."; hr; \
mi "$file" | grep -v '^Menu$' | grep -v '^[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}'; hr; \
ffprobe "$file" 2>&1 |grep Stream\ \#0:1 -A2; hr; \
opustags --delete METADATA_BLOCK_PICTURE -i "$file" && 
  echo "Removed cover with opustags"; hr; \
ffprobe "$file" 2>&1|grep Stream\ \#0:1 -A2 || echo "No cover found"; hr; \
mi "$file" | grep -v '^Menu$' | grep -v '^[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}'; hr

#########################################################################################################
Removed original comment and image (if present)
#########################################################################################################
General
Complete name                            : Violence and the Sacred -- Audiobook.opus
Format                                   : Ogg
File size                                : 112 MiB
Duration                                 : 17 h 50 min
Overall bit rate                         : 14.7 kb/s
Album                                    : Violence and the Sacred
Album/Performer                          : René Girard
Track name                               : Violence and the Sacred
Track name/Position                      : 1
Performer                                : René Girard
Composer                                 : Peter Noble
Publisher                                : HighBridge, a division of Recorded Books
Genre                                    : Politics & Social Sciences
Recorded date                            : 1972
Writing application                      : Lavc61.11.100 libopus

Audio
ID                                       : 3473298946 (0xCF065602)
Format                                   : Opus
Duration                                 : 17 h 50 min
Channel(s)                               : 1 channel
Channel layout                           : M
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Writing library                          : Lavf61.5.101
Language                                 : English



#########################################################################################################
Set cover with opustags
#########################################################################################################
Set description/comment with opustags.
#########################################################################################################
General
Complete name                            : Violence and the Sacred -- Audiobook.opus
Format                                   : Ogg
File size                                : 113 MiB
Duration                                 : 17 h 50 min
Overall bit rate                         : 14.8 kb/s
Album                                    : Violence and the Sacred
Album/Performer                          : René Girard
Track name                               : Violence and the Sacred
Track name/Position                      : 1
Performer                                : René Girard
Composer                                 : Peter Noble
Publisher                                : HighBridge, a division of Recorded Books
Genre                                    : Politics & Social Sciences
Recorded date                            : 1972
Writing application                      : Lavc61.11.100 libopus

Audio
ID                                       : 3473298946 (0xCF065602)
Format                                   : Opus
Duration                                 : 17 h 50 min
Channel(s)                               : 1 channel
Channel layout                           : M
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Writing library                          : Lavf61.5.101
Language                                 : English

Conformance errors                       : 1
 General compliance                      : Element size 736883 is more than maximal permitted size 583904 (conf, offset 0x7084766)


#########################################################################################################
  Stream #0:1: Video: mjpeg (Progressive), yuvj420p(pc, bt470bg/unknown/unknown), 2400x2400 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn (attached pic)
      Metadata:
        comment         : Cover (front)
#########################################################################################################
Removed cover with opustags
#########################################################################################################
No cover found
#########################################################################################################
General
Complete name                            : Violence and the Sacred -- Audiobook.opus
Format                                   : Ogg
File size                                : 112 MiB
Duration                                 : 17 h 50 min
Overall bit rate                         : 14.7 kb/s
Album                                    : Violence and the Sacred
Album/Performer                          : René Girard
Track name                               : Violence and the Sacred
Track name/Position                      : 1
Performer                                : René Girard
Composer                                 : Peter Noble
Publisher                                : HighBridge, a division of Recorded Books
Genre                                    : Politics & Social Sciences
Recorded date                            : 1972
Writing application                      : Lavc61.11.100 libopus
Comment                                  : "<p><em>Violence and the Sacred</em> is René Girard's landmark study of human evil. Here Girard explores violence as it is represented and occurs throughout history, literature, and myth. Girard's forceful and thought-provoking analyses of Biblical narrative, Greek tragedy, and the lynchings and pogroms propagated by contemporary states illustrate his central argument that violence belongs to everyone and is at the heart of the sacred.</p><p>Expanding on this, Girard argues that violence is not merely a breakdown of order but a constituent of it — ritualized, masked, and sacralized to hold society together. Through the lens of sacrifice and the scapegoat, he shows how the sacred emerges as a social technology for deflecting and containing violence. The very myths and religious rites we think of as transcendent, he suggests, may have their origins in blood and exclusion. It is a provocative and disturbing theory — one that reframes our understanding of culture, religion, and even justice.</p>"

Audio
ID                                       : 3473298946 (0xCF065602)
Format                                   : Opus
Duration                                 : 17 h 50 min
Channel(s)                               : 1 channel
Channel layout                           : M
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Writing library                          : Lavf61.5.101
Language                                 : English



#########################################################################################################
```

**Comment by JeromeMartinez** [comment]
> Ok, I'll wait until I either build 25.04 or it shows up in the Debian repo before further comment on the conformance issue.

We have [a Debian repo](https://mediaarea.net/Repos) as well as [direct .deb](https://mediaarea.net/MediaInfo/Download/Debian) (need to install the lib .deb) for installing new versions, you can easily test now.

> As I'm working on another book, there's an issue with how mediainfo reports out tags that are added after METADATA_BLOCK_PICTURE... i.e., it doesn't.

[I already answered to that](https://github.com/MediaArea/MediaInfoLib/issues/2285#issuecomment-2849407023).

With our WIP version we have this addition:
```
Image
Format                                   : JPEG
Muxing mode                              : Vorbis Comment / FLAC Picture
Width                                    : 2 400 pixels
Height                                   : 2 400 pixels
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Compression mode                         : Lossy
Stream size                              : 540 KiB (0%)
```

**Comment by iconoclasthero** [comment]
> > Ok, I'll wait until I either build 25.04 or it shows up in the Debian repo before further comment on the conformance issue.
> 
> We have [a Debian repo](https://mediaarea.net/Repos) as well as [direct .deb](https://mediaarea.net/MediaInfo/Download/Debian) (need to install the lib .deb) for installing new versions, you can easily test now.
> 

Ok, my OS is Rhino Linux 2025.2 and is presently pulling from the Questing/devel ubuntu repo but I've updated to the snapshot for Plucky:

```
$ mediainfo --version
MediaInfo Command line, 
MediaInfoLib - v25.04.20250503
```

> > As I'm working on another book, there's an issue with how mediainfo reports out tags that are added after METADATA_BLOCK_PICTURE... i.e., it doesn't.
> 
> [I already answered to that](https://github.com/MediaArea/MediaInfoLib/issues/2285#issuecomment-2849407023).

I didn't realize that comment addressed the issue of adding tags after embedding a cover image and the latter not being displayed.  The snapshot version is still not showing the comment/description tag updated/set/added after the cover.

> With our WIP version we have this addition:
> 
> ```
> Image
> Format                                   : JPEG
> Muxing mode                              : Vorbis Comment / FLAC Picture
> Width                                    : 2 400 pixels
> Height                                   : 2 400 pixels
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0
> Bit depth                                : 8 bits
> Compression mode                         : Lossy
> Stream size                              : 540 KiB (0%)
> ```

I'm not seeing this in the snapshot version.  Either I'm missing something or there aren't instructions to build MediaInfoLib so I'll wait until your WIP version rolls out.

Thanks.

**Comment by JeromeMartinez** [comment]
> Ok, my OS is Rhino Linux 2025.2 and is presently pulling from the Questing/devel ubuntu repo but I've updated to the snapshot for Plucky:

If this is resolved, please close this ticket (it is not related to the cover).

> I'm not seeing this in the snapshot version. Either I'm missing something or there aren't instructions to build MediaInfoLib so I'll wait until your WIP version rolls out.

It is WIP so not in snapshots.

**Comment by iconoclasthero** [comment]
I just noticed that I have snapshot version 25.04.20250515 and that it is reporting the size of embedded images in opus files and that the conformance error is gone.

And it appears that the order of attaching the cover does not inhibit the display of other tags.

Thank you.
